mra_Identity_client_fix-translate
srp-internships/MRA.Jobs pull request #521
Opened 2024-01-23 09:09 UTC by Ubaydulloev1104

2024-01-23 09:15 UTC, Muhammadislom99 approved these changes

2024-01-23 11:44 UTC, komdil requested changes

2024-01-23 11:44 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Client/Services/Profile/UserProfileService.cs
> +    private readonly HttpClient _httpClient = httpClient;
I think you should use our custom HttpClient inste4ad of HttpClient

2024-01-24 05:43 UTC, komdil requested changes

2024-01-24 05:43 UTC, komdil commented on src/MRA.Jobs.Identity/MRA.Identity.Client/Pages/Auth/Profile.razor
>                                                      <MudButton Variant="Variant.Filled" OnClick="SendEmailConfirms">
code is not formatted

2024-01-26 05:39 UTC, closed without merging